function klurf_make
%KLURF_MAKE compile the klurf (symbolic-once refactor) mexFunction.
% Real-valued, no CHOLMOD/METIS (AMD/COLAMD/BTF ordering only). Run from KLU/MATLAB.
d = '-largeArrayDims';
if (~verLessThan('matlab','8.3.0')); d = ['-silent ' d]; end
if (ispc); d = ['-DNTIMER -DNO_SSIZE_T ' d]; end
include = ['-DNCHOLMOD -DNLARGEFILE -I. -I../../AMD/Include -I../../COLAMD/Include ' ...
           '-I../Include -I../../SuiteSparse_config -I../../BTF/Include'];

src = { ...
    '../../SuiteSparse_config/SuiteSparse_config', ...
    '../../AMD/Source/amd_l1','../../AMD/Source/amd_l2','../../AMD/Source/amd_l_aat', ...
    '../../AMD/Source/amd_l_control','../../AMD/Source/amd_l_defaults','../../AMD/Source/amd_l_dump', ...
    '../../AMD/Source/amd_l_info','../../AMD/Source/amd_l_order','../../AMD/Source/amd_l_postorder', ...
    '../../AMD/Source/amd_l_post_tree','../../AMD/Source/amd_l_preprocess','../../AMD/Source/amd_l_valid', ...
    '../../COLAMD/Source/colamd_l', ...
    '../../BTF/Source/btf_l_maxtrans','../../BTF/Source/btf_l_order','../../BTF/Source/btf_l_strongcomp', ...
    '../Source/klu_l_free_symbolic','../Source/klu_l_defaults','../Source/klu_l_analyze_given', ...
    '../Source/klu_l_analyze','../Source/klu_l_memory', ...
    '../Source/klu_l','../Source/klu_l_kernel','../Source/klu_l_dump','../Source/klu_l_factor', ...
    '../Source/klu_l_free_numeric','../Source/klu_l_solve','../Source/klu_l_scale', ...
    '../Source/klu_l_refactor','../Source/klu_l_tsolve','../Source/klu_l_diagnostics', ...
    '../Source/klu_l_sort','../Source/klu_l_extract' };

if (ispc); ext = '.obj'; else; ext = '.o'; end
obj = '';
fprintf('Compiling klurf (real, no CHOLMOD)');
for f = src
    ff = f{1};
    sl = strfind(ff,'/'); if isempty(sl); sl=1; else; sl=sl(end)+1; end
    o  = [ff(sl:end) ext];
    obj = [obj ' ' o]; %#ok<AGROW>
    eval(sprintf('mex %s -O %s -c %s.c', d, include, ff));
    fprintf('.');
end
fprintf('\nLinking klurf mexFunction...\n');
eval(['mex ' d ' -O ' include ' -output klurf klurf_mex.c' obj]);
% keep object files for fast relink (klurf_relink.m)
save('klurf_objs.mat','obj');
fprintf('klurf successfully compiled\n');
end
